# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'
includes:
  ppy:
    taskfile: Taskfile.ppy.yaml
    optional: true
  nix:
    taskfile: nix/Taskfile.yaml
    dir: ./nix
    optional: true

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
