[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }

[tool_alias]
makejinja = "pipx:makejinja"
gh-cli = "aqua:cli/cli"
age = "aqua:FiloSottile/age"
sops = "aqua:getsops/sops"
task = "aqua:go-task/task"
jq = "aqua:jqlang/jq"
yq = "aqua:mikefarah/yq"
opencode = "aqua:anomalyco/opencode"
1password-cli = "aqua:1password/cli"

bat = "aqua:sharkdp/bat"
atuin = "aqua:atuinsh/atuin"
chezmoi = "aqua:twpayne/chezmoi"
carapace = "aqua:carapace-sh/carapace-bin"
direnv = "aqua:direnv/direnv"
fzf = "aqua:junegunn/fzf"
lazygit = "aqua:jesseduffield/lazygit"
rclone = "aqua:rclone/rclone"
yamlfmt = "aqua:google/yamlfmt"
exa = "aqua:ogham/exa"

[tools]
"python" = "3.14.4"
makejinja = "2.8.2"
gh-cli = "2.87.3"
age = "1.3.1"
sops = "3.12.2"
task = "3.48.0"
jq = "1.8.1"
yq = "4.52.4"
opencode = "1.2.10"
1password-cli = "2.31.1"

zoxide = "0.9.9"
bat = "0.26.1"
atuin = "18.12.1"
chezmoi = "2.69.4"
carapace = "1.6.2"
direnv = "2.37.1"
fzf = "0.68.0"
lazygit = "0.59.0"
neovim = "latest"
rclone = "1.73.1"
yt-dlp = "2026.02.04"
yamllint = "1.38.0"
yamlfmt = "0.21.0"
go = "1.26.1" # generally good to have 
node = "25.8.1" # for vim plugins
pipx = "1.11.0"
uv = "0.11.0"
rust = "1.94.0"
starship = "1.24.2"
exa = "0.10.1"
terraform = "1.14.7"
bun = "1.3.11"
"github:can1357/oh-my-pi" = "13.14.2"
